# Use root/toor as user/password credentials
version: '3.1'

services:
  mysql:
    container_name: nivel3-db
    command: --default-authentication-plugin=mysql_native_password
    build:
        context: .
        dockerfile: db/Dockerfile
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python:
    container_name: nivel3-app
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000

  redis:
    image: redis
    expose:
       - 6379
